In [ ]:
import keras 
import pandas as pd 
import numpy as np 
from sklearn.preprocessing import normalize

In [ ]:
data=pd.read_csv("/content/drive/MyDrive/Colab/Iris.csv")

In [ ]:
#Coding below convert the species into each respective category to be feed into the neural network

print(data["Species"].unique())

['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


In [ ]:
data.loc[data["Species"]=="Iris-setosa","Species"]=0
data.loc[data["Species"]=="Iris-versicolor","Species"]=1
data.loc[data["Species"]=="Iris-virginica","Species"]=2
print(data.head())

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm Species
0   1            5.1           3.5            1.4           0.2       0
1   2            4.9           3.0            1.4           0.2       0
2   3            4.7           3.2            1.3           0.2       0
3   4            4.6           3.1            1.5           0.2       0
4   5            5.0           3.6            1.4           0.2       0


In [ ]:
data=data.iloc[np.random.permutation(len(data))]
print(data.head())

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm Species
39    40            5.1           3.4            1.5           0.2       0
7      8            5.0           3.4            1.5           0.2       0
33    34            5.5           4.2            1.4           0.2       0
128  129            6.4           2.8            5.6           2.1       2
97    98            6.2           2.9            4.3           1.3       1


In [ ]:
#Converting data to numpy array in order for processing

X=data.iloc[:,1:5].values
y=data.iloc[:,5].values


In [ ]:
#Normalization

X_normalized=normalize(X,axis=0)

In [ ]:
total_length=len(data)
train_length=int(0.8*total_length)
test_length=int(0.2*total_length)

X_train=X_normalized[:train_length]
X_test=X_normalized[train_length:]
y_train=y[:train_length]
y_test=y[train_length:]

In [ ]:
#Neural network module
from keras.models import Sequential 
from keras.layers import Dense,Activation,Dropout 
from tensorflow.keras.layers import BatchNormalization
from keras.utils import np_utils

In [ ]:
y_train=np_utils.to_categorical(y_train,num_classes=3)
y_test=np_utils.to_categorical(y_test,num_classes=3)

In [ ]:
model=Sequential()
model.add(Dense(1000,input_dim=4,activation='relu'))
model.add(Dense(500,activation='relu'))
model.add(Dense(300,activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(3,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 1000)              5000      
_________________________________________________________________
dense_1 (Dense)              (None, 500)               500500    
_________________________________________________________________
dense_2 (Dense)              (None, 300)               150300    
_________________________________________________________________
dropout (Dropout)            (None, 300)               0         
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 903       
Total params: 656,703
Trainable params: 656,703
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),batch_size=20,epochs=10,verbose=1)

Epoch 1/10
6/6 [==============================] - 1s 41ms/step - loss: 1.0803 - accuracy: 0.3917 - val_loss: 1.0678 - val_accuracy: 0.2667
Epoch 2/10
6/6 [==============================] - 0s 10ms/step - loss: 1.0083 - accuracy: 0.5917 - val_loss: 0.9769 - val_accuracy: 0.6333
Epoch 3/10
6/6 [==============================] - 0s 10ms/step - loss: 0.8759 - accuracy: 0.6750 - val_loss: 0.8246 - val_accuracy: 0.6333
Epoch 4/10
6/6 [==============================] - 0s 9ms/step - loss: 0.7042 - accuracy: 0.6750 - val_loss: 0.6066 - val_accuracy: 0.6333
Epoch 5/10
6/6 [==============================] - 0s 10ms/step - loss: 0.5088 - accuracy: 0.8000 - val_loss: 0.3939 - val_accuracy: 1.0000
Epoch 6/10
6/6 [==============================] - 0s 10ms/step - loss: 0.3866 - accuracy: 0.9167 - val_loss: 0.3514 - val_accuracy: 0.8667
Epoch 7/10
6/6 [==============================] - 0s 10ms/step - loss: 0.3045 - accuracy: 0.9167 - val_loss: 0.1872 - val_accuracy: 1.0000
Epoch 8/10
6/6 [============

In [18]:
prediction=model.predict(X_test)
y_test_class  = np.argmax(y_test, axis =1)
y_pred_class = np.argmax(prediction, axis =1)



In [20]:
from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      0.64      0.78        11
           2       0.64      1.00      0.78         7

    accuracy                           0.87        30
   macro avg       0.88      0.88      0.85        30
weighted avg       0.92      0.87      0.87        30

[[12  0  0]
 [ 0  7  4]
 [ 0  0  7]]
