In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
import keras 
import pandas as pd 
import numpy as np 
from sklearn.preprocessing import normalize

In [3]:
data=pd.read_csv("/content/drive/MyDrive/Colab/Iris.csv")

In [4]:
#Coding below convert the species into each respective category to be feed into the neural network

print(data["Species"].unique())

['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


In [5]:
data.loc[data["Species"]=="Iris-setosa","Species"]=0
data.loc[data["Species"]=="Iris-versicolor","Species"]=1
data.loc[data["Species"]=="Iris-virginica","Species"]=2
print(data.head())

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm Species
0   1            5.1           3.5            1.4           0.2       0
1   2            4.9           3.0            1.4           0.2       0
2   3            4.7           3.2            1.3           0.2       0
3   4            4.6           3.1            1.5           0.2       0
4   5            5.0           3.6            1.4           0.2       0


In [6]:
data=data.iloc[np.random.permutation(len(data))]
print(data.head())

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm Species
135  136            7.7           3.0            6.1           2.3       2
115  116            6.4           3.2            5.3           2.3       2
4      5            5.0           3.6            1.4           0.2       0
107  108            7.3           2.9            6.3           1.8       2
52    53            6.9           3.1            4.9           1.5       1


In [7]:
#Converting data to numpy array in order for processing

X=data.iloc[:,1:5].values
y=data.iloc[:,5].values


In [8]:
#Normalization

X_normalized=normalize(X,axis=0)

In [9]:
print(X_normalized)

[[0.10653575 0.07941484 0.12002387 0.13228444]
 [0.0885492  0.08470916 0.10428304 0.13228444]
 [0.06917906 0.09529781 0.02754646 0.01150299]
 [0.10100143 0.07676768 0.12395908 0.10352695]
 [0.0954671  0.082062   0.09641262 0.08627246]
 [0.07471338 0.10323929 0.02557886 0.02300599]
 [0.07609697 0.06353187 0.07476897 0.06326647]
 [0.08024771 0.06882619 0.07870418 0.06901797]
 [0.07056264 0.09000348 0.02951407 0.01150299]
 [0.06364474 0.08470916 0.02754646 0.01150299]
 [0.07056264 0.08735632 0.03344928 0.02875749]
 [0.07056264 0.09265065 0.02754646 0.01725449]
 [0.06917906 0.09265065 0.03148167 0.03450898]
 [0.07886413 0.06617903 0.09838022 0.11502995]
 [0.0954671  0.08470916 0.11215345 0.13228444]
 [0.10238501 0.07412052 0.12002387 0.10927845]
 [0.07471338 0.07941484 0.0885422  0.08627246]
 [0.08024771 0.07147336 0.08067178 0.05751497]
 [0.07194622 0.09000348 0.02754646 0.01150299]
 [0.07609697 0.09265065 0.02557886 0.01150299]
 [0.08301487 0.05823755 0.09838022 0.08627246]
 [0.08993278 

In [10]:
total_length=len(data)
train_length=int(0.8*total_length)
test_length=int(0.2*total_length)

X_train=X_normalized[:train_length]
X_test=X_normalized[train_length:]
y_train=y[:train_length]
y_test=y[train_length:]

In [11]:
#Neural network module
from keras.models import Sequential 
from keras.layers import Dense,Activation,Dropout 
from tensorflow.keras.layers import BatchNormalization
from keras.utils import np_utils

In [12]:
y_train=np_utils.to_categorical(y_train,num_classes=3)
y_test=np_utils.to_categorical(y_test,num_classes=3)

In [13]:
model=Sequential()
model.add(Dense(1000,input_dim=4,activation='relu'))
model.add(Dense(500,activation='relu'))
model.add(Dense(300,activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(3,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 1000)              5000      
_________________________________________________________________
dense_1 (Dense)              (None, 500)               500500    
_________________________________________________________________
dense_2 (Dense)              (None, 300)               150300    
_________________________________________________________________
dropout (Dropout)            (None, 300)               0         
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 903       
Total params: 656,703
Trainable params: 656,703
Non-trainable params: 0
_________________________________________________________________


In [15]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),batch_size=20,epochs=10,verbose=1)

Epoch 1/10
6/6 [==============================] - 1s 42ms/step - loss: 1.0794 - accuracy: 0.5083 - val_loss: 1.0502 - val_accuracy: 0.6667
Epoch 2/10
6/6 [==============================] - 0s 11ms/step - loss: 1.0100 - accuracy: 0.6500 - val_loss: 0.9383 - val_accuracy: 0.6667
Epoch 3/10
6/6 [==============================] - 0s 10ms/step - loss: 0.8639 - accuracy: 0.6667 - val_loss: 0.7487 - val_accuracy: 0.6667
Epoch 4/10
6/6 [==============================] - 0s 11ms/step - loss: 0.6584 - accuracy: 0.7000 - val_loss: 0.5171 - val_accuracy: 0.8333
Epoch 5/10
6/6 [==============================] - 0s 11ms/step - loss: 0.4567 - accuracy: 0.8750 - val_loss: 0.3540 - val_accuracy: 0.9333
Epoch 6/10
6/6 [==============================] - 0s 13ms/step - loss: 0.3256 - accuracy: 0.9250 - val_loss: 0.3032 - val_accuracy: 0.9333
Epoch 7/10
6/6 [==============================] - 0s 12ms/step - loss: 0.2851 - accuracy: 0.9167 - val_loss: 0.1979 - val_accuracy: 0.9667
Epoch 8/10
6/6 [===========

In [16]:
prediction=model.predict(X_test)
y_test_class  = np.argmax(y_test, axis =1)
y_pred_class = np.argmax(prediction, axis =1)



In [17]:
from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      1.00      1.00        10
           2       1.00      1.00      1.00         9

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

[[11  0  0]
 [ 0 10  0]
 [ 0  0  9]]
